# Generated by Django 2.0.6 on 2018-07-24 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='isTrackITClient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='trackITRoleType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Roles'),
        ),
    ]
