# Generated by Django 2.0.6 on 2018-07-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='isTrackITClient',
            field=models.BooleanField(default=False),
        ),
    ]
