# Generated by Django 2.0.6 on 2018-07-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180723_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='isTrackITAgent',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='isTrackITClient',
        ),
    ]
