# Generated by Django 2.0.6 on 2018-07-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_tickets_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
