# Generated by Django 2.0.6 on 2018-07-15 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180714_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='foo',
            new_name='slug',
        ),
    ]
