# Generated by Django 2.0.6 on 2018-07-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180714_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='attachment',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
