# Generated by Django 2.0.6 on 2018-07-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_tickets_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='archived',
            new_name='resolved',
        ),
    ]
